/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author GerardoG
 */
public class VentanaAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAdministrador
     */
    
    //Ventanas
    
    LoginVista vntLogin;
    InternaModeloCrear internaModelo;
    InternaModeloB_A_E internaModeloB_A_E;
    
    InternaMarcaCrear internaMarca;
    InternaMarcaB_A_E internaMarcaB_A_E;
    
    InternaTipoAutoCrear internaTipoAuto;
    InternaTipoB_A_E internaTipoAutoB_A_E;
    
    InternaAutoCrear internaAuto;
    InternaAutoB_A_E internaAutoB_A_E;
    InternaAutosListar internaAutosListar;
    
    InternaUsuariosCrear internaUsuario;
    InternaUsuariosB_A_E internaUsuarioB_A_E;
    
    InternaUsuarioListar internaUsuarioListar;
    
    

    public VentanaAdministrador(String usuario,String nomSuc) {
        initComponents();
        setLocationRelativeTo(null);
        txtnombre.setText(usuario);
        txtsucursal.setText(nomSuc);
    }

    private VentanaAdministrador() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        txtnombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtsucursal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuCrear = new javax.swing.JMenuItem();
        jMenuAutoA_E = new javax.swing.JMenuItem();
        jMenuItemListarAutos = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItemCrear = new javax.swing.JMenuItem();
        jMenuA_E = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuModelo = new javax.swing.JMenuItem();
        jMenuAE = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuCrearTip = new javax.swing.JMenuItem();
        jMenuA_E_Tipo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuCrearUsuarios = new javax.swing.JMenuItem();
        jMenuUsuariosB_A_E = new javax.swing.JMenuItem();
        jMenuItemListarUsuario = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jDesktopPane1.setBackground(new java.awt.Color(153, 255, 255));
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtnombre.setForeground(new java.awt.Color(255, 255, 255));
        txtnombre.setEnabled(false);
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        jDesktopPane1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 54, 160, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bienvenido Administrador");
        jDesktopPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(752, 32, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sucursal");
        jDesktopPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(752, 92, -1, -1));

        txtsucursal.setForeground(new java.awt.Color(255, 255, 255));
        txtsucursal.setEnabled(false);
        txtsucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsucursalActionPerformed(evt);
            }
        });
        jDesktopPane1.add(txtsucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 114, 160, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alquiler-de-autos-10102017.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jDesktopPane1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 480));

        jMenu1.setText("Automovil");

        jMenu8.setText("Auto");

        jMenuCrear.setText("Crear");
        jMenuCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCrearActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuCrear);

        jMenuAutoA_E.setText("Actualizar o Eliminar");
        jMenuAutoA_E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAutoA_EActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuAutoA_E);

        jMenuItemListarAutos.setText("Listar");
        jMenuItemListarAutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarAutosActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItemListarAutos);

        jMenu1.add(jMenu8);

        jMenu6.setText("Marca");

        jMenuItemCrear.setText("Crear");
        jMenuItemCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrearActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemCrear);

        jMenuA_E.setText("Actualizar o Eliminar");
        jMenuA_E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuA_EActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuA_E);

        jMenu1.add(jMenu6);

        jMenu5.setText("Modelo");

        jMenuModelo.setText("Crear");
        jMenuModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuModeloActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuModelo);

        jMenuAE.setText("Actualizar o Eliminar");
        jMenuAE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAEActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuAE);

        jMenu1.add(jMenu5);

        jMenu7.setText("Tipo Auto");

        jMenuCrearTip.setText("Crear");
        jMenuCrearTip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCrearTipActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuCrearTip);

        jMenuA_E_Tipo.setText("Actualizar o Eliminar");
        jMenuA_E_Tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuA_E_TipoActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuA_E_Tipo);

        jMenu1.add(jMenu7);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Usuarios");

        jMenuCrearUsuarios.setText("Crear");
        jMenuCrearUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCrearUsuariosActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuCrearUsuarios);

        jMenuUsuariosB_A_E.setText("Actualizar o Eliminar");
        jMenuUsuariosB_A_E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuariosB_A_EActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuUsuariosB_A_E);

        jMenuItemListarUsuario.setText("Listar");
        jMenuItemListarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarUsuarioActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemListarUsuario);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Opciones");

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtsucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsucursalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsucursalActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        setVisible(false);
        vntLogin = new LoginVista();
        vntLogin.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuModeloActionPerformed
        if(internaModelo == null || !internaModelo.isVisible()){
        internaModelo = new InternaModeloCrear();
        jDesktopPane1.add(internaModelo);
        internaModelo.show();
        }
    }//GEN-LAST:event_jMenuModeloActionPerformed

    private void jMenuAEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAEActionPerformed
        if(internaModeloB_A_E == null || !internaModeloB_A_E.isVisible()){
        internaModeloB_A_E = new InternaModeloB_A_E();
        jDesktopPane1.add(internaModeloB_A_E);
        internaModeloB_A_E.show();
        }
    }//GEN-LAST:event_jMenuAEActionPerformed

    private void jMenuCrearTipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCrearTipActionPerformed
        if(internaTipoAuto == null || !internaTipoAuto.isVisible()){
        internaTipoAuto = new InternaTipoAutoCrear();
        jDesktopPane1.add(internaTipoAuto);
        internaTipoAuto.show();
        }
    }//GEN-LAST:event_jMenuCrearTipActionPerformed

    private void jMenuA_E_TipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuA_E_TipoActionPerformed
        if(internaTipoAutoB_A_E == null || !internaTipoAutoB_A_E.isVisible()){
        internaTipoAutoB_A_E = new InternaTipoB_A_E();
        jDesktopPane1.add(internaTipoAutoB_A_E);
        internaTipoAutoB_A_E.show();
        }
    }//GEN-LAST:event_jMenuA_E_TipoActionPerformed

    private void jMenuA_EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuA_EActionPerformed
        if(internaMarcaB_A_E == null || !internaMarcaB_A_E.isVisible()){
            internaMarcaB_A_E = new InternaMarcaB_A_E();
            jDesktopPane1.add(internaMarcaB_A_E);
            internaMarcaB_A_E.show();
        }
    }//GEN-LAST:event_jMenuA_EActionPerformed

    private void jMenuItemCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrearActionPerformed
        if(internaMarca == null || !internaMarca.isVisible()){
            internaMarca = new InternaMarcaCrear();
            jDesktopPane1.add(internaMarca);
            internaMarca.show();
        }
    }//GEN-LAST:event_jMenuItemCrearActionPerformed

    private void jMenuCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCrearActionPerformed
        if(internaAuto == null || !internaAuto.isVisible()){
            internaAuto = new InternaAutoCrear(txtsucursal.getText());
            jDesktopPane1.add(internaAuto);
            internaAuto.show();
        }
    }//GEN-LAST:event_jMenuCrearActionPerformed

    private void jMenuAutoA_EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAutoA_EActionPerformed
        if(internaAutoB_A_E == null || !internaAutoB_A_E.isVisible()){
            internaAutoB_A_E = new InternaAutoB_A_E();
            jDesktopPane1.add(internaAutoB_A_E);
            internaAutoB_A_E.show();
        }
    }//GEN-LAST:event_jMenuAutoA_EActionPerformed

    private void jMenuCrearUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCrearUsuariosActionPerformed
        if(internaUsuario == null || !internaUsuario.isVisible()){
            internaUsuario = new InternaUsuariosCrear();
            jDesktopPane1.add(internaUsuario);
            internaUsuario.show();
        }
    }//GEN-LAST:event_jMenuCrearUsuariosActionPerformed

    private void jMenuUsuariosB_A_EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuariosB_A_EActionPerformed
        if(internaUsuarioB_A_E == null || !internaUsuarioB_A_E.isVisible()){
            internaUsuarioB_A_E = new InternaUsuariosB_A_E();
            jDesktopPane1.add(internaUsuarioB_A_E);
            internaUsuarioB_A_E.show();
        }
    }//GEN-LAST:event_jMenuUsuariosB_A_EActionPerformed

    private void jMenuItemListarAutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarAutosActionPerformed
         if(internaAutosListar == null || !internaAutosListar.isVisible()){
            internaAutosListar = new InternaAutosListar();
            jDesktopPane1.add(internaAutosListar);
            internaAutosListar.show();
        }
    }//GEN-LAST:event_jMenuItemListarAutosActionPerformed

    private void jMenuItemListarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarUsuarioActionPerformed
        if(internaUsuarioListar == null || !internaUsuarioListar.isVisible()){
            internaUsuarioListar = new InternaUsuarioListar();
            jDesktopPane1.add(internaUsuarioListar);
            internaUsuarioListar.show();
        }
    }//GEN-LAST:event_jMenuItemListarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuItem jMenuAE;
    private javax.swing.JMenuItem jMenuA_E;
    private javax.swing.JMenuItem jMenuA_E_Tipo;
    private javax.swing.JMenuItem jMenuAutoA_E;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCrear;
    private javax.swing.JMenuItem jMenuCrearTip;
    private javax.swing.JMenuItem jMenuCrearUsuarios;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItemCrear;
    private javax.swing.JMenuItem jMenuItemListarAutos;
    private javax.swing.JMenuItem jMenuItemListarUsuario;
    private javax.swing.JMenuItem jMenuModelo;
    private javax.swing.JMenuItem jMenuUsuariosB_A_E;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtsucursal;
    // End of variables declaration//GEN-END:variables
}
